var num = null;
console.log('num', num = num);
var bool = null;
console.log('bool', bool = bool);
var str = null;
console.log('str', str = str);
var n = null;
console.log('n', n = n);
//# sourceMappingURL=null.js.map